apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app.kubernetes.io/name: testblog
  name: testblog
spec:
  output:
    to:
      kind: DockerImage
      name: docker.io/"USER ID"/testblog:latest
  source:     
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
